apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: simple-app
  namespace: default
  annotations:
    kapp.k14s.io/change-rule: upsert after upserting pkg
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: simple-app-overlay
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: pkg.test.carvel.dev
    versionSelection:
      constraints: 2.0.0
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-app-overlay
  namespace: default
stringData:
  overlay.yml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "Deployment"})
    ---
    spec:
      #@overlay/match missing_ok=True
      replicas: 5
